### ISSUE TITLE
Error spamming console with 1.8.0.1

### ISSUE THREAD

**Issue by MasterLuke117** [Nukkit-coders/MobPlugin#108]
```04:27:09 [ERROR] Could not tick level "{%0}": {%1}
java.lang.NullPointerException: null
at cn.nukkit.item.enchantment.Enchantment.getEnchantment(Enchantment.java:113) ~[server.jar:?]
at cn.nukkit.item.Item.getEnchantments(Item.java:630) ~[server.jar:?]
at cn.nukkit.entity.EntityHumanType.calculateEnchantmentReduction(EntityHumanType.java:193) ~[server.jar:?]
at cn.nukkit.entity.EntityHumanType.attack(EntityHumanType.java:133) ~[server.jar:?]
at cn.nukkit.Player.attack(Player.java:3996) ~[server.jar:?]
at nukkitcoders.mobplugin.entities.monster.walking.Zombie.attackEntity(Zombie.java:112) ~[?:?]
at nukkitcoders.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:159) ~[?:?]
at cn.nukkit.level.Level.doTick(Level.java:782) ~[server.jar:?]
at cn.nukkit.Server.checkTickUpdates(Server.java:1053) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1134) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:903) [server.jar:?]
at cn.nukkit.Server.start(Server.java:880) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:565) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]```

**Comment by PetteriM1** [comment]
Seems to be a Nukkit bug

**Comment by PetteriM1** [comment]
When does this error appear?

**Comment by PetteriM1** [comment]
I guess this is fixed in the latest Nukkit build
