### ISSUE TITLE
CreatureSpawnError

### ISSUE THREAD

**Issue by GACastro95** [Nukkit-coders/MobPlugin#123]
2019-08-24 05:50:45.452 [main] INFO  - Enabling MobPlugin v1.10.3
2019-08-24 05:50:45.455 [main] ERROR - Throwing
java.lang.RuntimeException: java.lang.NoClassDefFoundError: cn/nukkit/event/entity/CreatureSpawnEvent
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [nukkit.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:733) [nukkit.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:722) [nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:483) [nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?]
Caused by: java.lang.NoClassDefFoundError: cn/nukkit/event/entity/CreatureSpawnEvent
	at nukkitcoders.mobplugin.MobPlugin.onEnable(MobPlugin.java:68) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[nukkit.jar:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: cn.nukkit.event.entity.CreatureSpawnEvent
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:34) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[nukkit.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at nukkitcoders.mobplugin.MobPlugin.onEnable(MobPlugin.java:68) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[nukkit.jar:?]
	... 4 more

**Comment by PetteriM1** [comment]
Update Nukkit
