### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by DueKay** [Nukkit-coders/MobPlugin#130]
Unfortunately I have an error message today
I hope this can be fixed quickly. I never had before and comes in quite often.

[36m14:31:11[m [[m[1;31mERROR[m[m] Fehler beim Entladen eines Chunks: cn.nukkit.utils.ChunkException: Error saving chunk (0, -26) 
[36m14:31:11[m [[m[1;31mERROR[m[m] Throwing 
cn.nukkit.utils.ChunkException: Error saving chunk (0, -26) 
at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:237) ~[nukkit.jar:?] 
at cn.nukkit.level.Level.unloadChunk(Level.java:2782) [nukkit.jar:?] 
at cn.nukkit.level.Level.unloadChunk(Level.java:2744) [nukkit.jar:?] 
at cn.nukkit.level.Level.unloadChunks(Level.java:3116) [nukkit.jar:?] 
at cn.nukkit.level.Level.doGarbageCollection(Level.java:3014) [nukkit.jar:?] 
at cn.nukkit.Server.tickProcessor(Server.java:916) [nukkit.jar:?] 
at cn.nukkit.Server.start(Server.java:880) [nukkit.jar:?] 
at cn.nukkit.Server.<init>(Server.java:565) [nukkit.jar:?] 
at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?] 
Caused by: java.lang.NullPointerException 
at nukkitcoders.mobplugin.entities.monster.walking.Wolf.saveNBT(Wolf.java:80) ~[?:?] 
at cn.nukkit.level.format.anvil.Chunk.toBinary(Chunk.java:382) ~[nukkit.jar:?] 
at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:152) ~[nukkit.jar:?] 
at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:235) ~[nukkit.jar:?] 
... 8 more

Greetings DueKay

**Comment by PetteriM1** [comment]
Seems to be an error with wolf collar color saving. Do you have any idea how to reproduce this error?

**Comment by DueKay** [comment]
I have an idea why it might be...
We have recently distributed the first pets on our server. For this we used name tags, so they can't despawn.
I would think that the mistake is related to that. But I am not sure...

**Comment by PetteriM1** [comment]
> I have an idea why it might be...
> We have recently distributed the first pets on our server. For this we used name tags, so they can't despawn.
> I would think that the mistake is related to that. But I am not sure...

Might be. Pets plugin have had problems with mob plugin before.

**Comment by DueKay** [comment]
I do not use a Pet Plugin ^^
At least for now. May be that we still have our own add :)
We use the name tags to have the animals permanently on the GS. And I believe that the Fehhler is connected with it! One of the animals of the users, who has a name tag, can not always move again. For the other 4 are so far no problems. But that was the only change in recent times. Why I assume that it is because!
