### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by MasterLuke117** [Nukkit-coders/MobPlugin#145]
```
> java.lang.ClassCastException: cn.nukkit.level.Location cannot be cast to cn.nukkit.entity.Entity
at nukkitcoders.mobplugin.entities.BaseEntity.getFollowTarget(BaseEntity.java:79)
at nukkitcoders.mobplugin.route.WalkerRouteFinder.search(WalkerRouteFinder.java:61)
at nukkitcoders.mobplugin.route.RouteFinder.research(RouteFinder.java:156)
at nukkitcoders.mobplugin.runnable.RouteFinderSearchTask.run(RouteFinderSearchTask.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
04:04:52 [INFO ] [BugReport] An error has been detected, creating a bug report.
> 04:04:52 [INFO ] [BugReport] A bug report has been created: /home/container/logs/bug_reports/202002160404584_ClassCastException.md```


<!--- Please do not ask questions or create discussion in the bug tracker. Use https://nukkitx.com -->
<!--- ONLY POST ISSUES WITH A CLEAN SERVER ON THE LATEST VERSION -->
## Generated Bug Report

<!--- DO NOT OPEN A ISSUE IF THIS IS A PLUGIN ERROR -->
PLUGIN ERROR: TRUE

### Expected Behavior
<!--- What would you expect to happen -->


### Actual Behavior
<!--- What actually happened -->


### Steps to Reproduce
<!--- Reliable steps which someone can use to reproduce the issue. Please do not create issues for non reproducible bug! -->


### OS and Versions

* Nukkit Version: git-e4c0f7f 
* Java Version: OpenJDK 64-Bit Server VM (1.8.0_212-8u212-b01-1~deb9u1-b01)

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Linux-amd64 [4.15.0-76-generic] |  
| Memory(RAM) | 202.8 GB | 
| Storage Size | 2.0 TB | 
| Storage Type | Disk 0:(avail=1.2 TB, total=2.0 TB)  | 
| CPU Type | UNKNOWN | 
| CPU Core Count | 8 | 

### Crashdump, Backtrace or Other Files

```
java.lang.ClassCastException: cn.nukkit.level.Location cannot be cast to cn.nukkit.entity.Entity
	at nukkitcoders.mobplugin.entities.BaseEntity.getFollowTarget(BaseEntity.java:79)
	at nukkitcoders.mobplugin.route.WalkerRouteFinder.search(WalkerRouteFinder.java:61)
	at nukkitcoders.mobplugin.route.RouteFinder.research(RouteFinder.java:156)
	at nukkitcoders.mobplugin.runnable.RouteFinderSearchTask.run(RouteFinderSearchTask.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by PetteriM1** [comment]
What version is that?
