### ISSUE TITLE
nukkit2.0

### ISSUE THREAD

**Issue by 1532600447** [Nukkit-coders/MobPlugin#148]
`18:14:50 [FATAL] Nukkit crashed
java.lang.NoClassDefFoundError: cn/nukkit/math/Vector3
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_242]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_242]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_242]
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_242]
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:59) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:97) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:266) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:134) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:126) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:122) ~[Nukkit.jar:?]
        at cn.nukkit.Server.boot(Server.java:510) ~[Nukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:139) ~[Nukkit.jar:?]
Caused by: java.lang.ClassNotFoundException: cn.nukkit.math.Vector3
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:34) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[Nukkit.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
        ... 12 more
18:14:50 [INFO ] Stopping other threadss`

**Comment by PetteriM1** [comment]
This plugin does not support Nukkit 2.0

**Comment by 1532600447** [comment]
Excuse me, when will 2.0 be developed

**Comment by 1532600447** [comment]
Excuse me, when will 2.0 be developed

**Comment by PetteriM1** [comment]
> Excuse me, when will 2.0 be developed

Maybe after 2.0 release if I have time
