### ISSUE TITLE
Mobs don't hit the player

### ISSUE THREAD

**Issue by Jl1mbo** [Nukkit-coders/MobPlugin#198]
### Info

This is:
- [X ] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
2020-09-01 10:23:49.439 [main] ERROR - Ошибка прорисовки мира "world": java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at nukkitcoders.mobplugin.entities.monster.WalkingMonster.getMinDamage(WalkingMonster.java:50)
	at nukkitcoders.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:39)
	at nukkitcoders.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:35)
	at nukkitcoders.mobplugin.entities.monster.walking.Zombie.attackEntity(Zombie.java:86)
	at nukkitcoders.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:159)
	at cn.nukkit.level.Level.doTick(Level.java:863)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1212)
	at cn.nukkit.Server.tick(Server.java:1294)
	at cn.nukkit.Server.tickProcessor(Server.java:1066)
	at cn.nukkit.Server.start(Server.java:1034)
	at cn.nukkit.Server.<init>(Server.java:695)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)```

```

### Configuration
Link to debugpaste:
```

```
Config:
```

```

**Comment by PetteriM1** [comment]
What is your server's difficulty?

**Comment by Jl1mbo** [comment]
> What is your server's difficulty?

In the sense?

**Comment by Jl1mbo** [comment]
hastebin.com/oxuladaxum

**Comment by PetteriM1** [comment]
4 is not a valid value for difficulty
