### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by SS-YG** [Nukkit-coders/MobPlugin#201]
java.lang.ClassCastException: Cannot cast nukkitcoders.mobplugin.entities.monster.walking.Enderman to cn.nukkit.Player
        at java.lang.invoke.MethodHandleImpl.newClassCastException(Unknown Source)
        at java.lang.invoke.MethodHandleImpl.castReference(Unknown Source)
        at jdk.nashorn.internal.scripts.Script$Recompilation$76$18935A$\^eval\_.EntityDamageEvent(<eval>:522)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
        at com.blocklynukkit.loader.Loader.callEventHandler(Loader.java:333)
        at com.blocklynukkit.loader.EventLoader.onEntityDamage(EventLoader.java:239)
        at sun.reflect.GeneratedMethodAccessor277.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:579)
        at cn.nukkit.entity.Entity.attack(Entity.java:1188)
        at cn.nukkit.entity.EntityLiving.attack(EntityLiving.java:115)
        at nukkitcoders.mobplugin.entities.BaseEntity.attack(BaseEntity.java:183)
        at nukkitcoders.mobplugin.entities.monster.walking.Enderman.attack(Enderman.java:81)
        at nukkitcoders.mobplugin.entities.monster.walking.Enderman.entityBaseTick(Enderman.java:122)
        at nukkitcoders.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:154)
        at cn.nukkit.level.Level.doTick(Level.java:863)
        at cn.nukkit.Server.checkTickUpdates(Server.java:1212)
        at cn.nukkit.Server.tick(Server.java:1294)
        at cn.nukkit.Server.tickProcessor(Server.java:1066)
        at cn.nukkit.Server.start(Server.java:1034)
        at cn.nukkit.Server.<init>(Server.java:695)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)

**Comment by PetteriM1** [comment]
The issue seems to be caused by Blocklynukkit, not by the mob plugin

**Comment by zombihunterbonn** [comment]
Lol wrong page lul
