### ISSUE TITLE
Creeper fix didnt fix creepers.

### ISSUE THREAD

**Issue by MrRazamataz** [Nukkit-coders/MobPlugin#211]
### Info

This is:
- [X] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
They just go white and disappear or stay white.
[Video](https://youtu.be/UnUP4-zFIwk)
### Configuration
Link to debugpaste:
```
COMPATABILITY ERROR: 
02:11:27 [FATAL] Could not pass event "cn.nukkit.event.entity.EntityExplosionPrimeEvent" to "Rollback v1.0-SNAPSHOT": null on com.boydti.rollback.CoreEvent
02:11:27 [ERROR] Throwing
cn.nukkit.utils.EventException: null
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:33) ~[server.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:577) [server.jar:?]
at nukkitcoders.mobplugin.entities.monster.walking.Creeper.explode(Creeper.java:79) [MobPlugin-1.17.1.jar:?]
at nukkitcoders.mobplugin.entities.monster.walking.Creeper.entityBaseTick(Creeper.java:192) [MobPlugin-1.17.1.jar:?]
at nukkitcoders.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:154) [MobPlugin-1.17.1.jar:?]
at cn.nukkit.level.Level.doTick(Level.java:943) [server.jar:?]
at cn.nukkit.Server.checkTickUpdates(Server.java:1295) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1377) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:1142) [server.jar:?]
at cn.nukkit.Server.start(Server.java:1102) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:762) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
Caused by: java.lang.ClassCastException: nukkitcoders.mobplugin.entities.monster.walking.Creeper cannot be cast to cn.nukkit.entity.item.EntityPrimedTNT
at com.boydti.rollback.CoreEvent.onBlockExplode(CoreEvent.java:286) ~[Rollback-1.0-SNAPSHOT.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:28) ~[server.jar:?]
... 12 more
02:11:31 [INFO ] [Player] <IamNotRaihan> and you accidentally picked it up
02:11:35 [INFO ] [MrRazamataz2006: Set own game mode to Creative Mode]
02:11:35 [INFO ] [Player] <aresarkansan> IM BACK FROM THE DEDD
02:11:35 [INFO ] [Player] <DressierPen9301> Let me tp isa
02:11:46 [INFO ] [MrRazamataz2006: Set own game mode to Survival Mode]
02:11:47 [INFO ] [Player] <ItsIsabel01> i might retract my bid
02:11:48 [FATAL] Could not pass event "cn.nukkit.event.entity.EntityExplosionPrimeEvent" to "Rollback v1.0-SNAPSHOT": null on com.boydti.rollback.CoreEvent
02:11:48 [ERROR] Throwing
cn.nukkit.utils.EventException: null
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:33) ~[server.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:577) [server.jar:?]
at nukkitcoders.mobplugin.entities.monster.walking.Creeper.explode(Creeper.java:79) [MobPlugin-1.17.1.jar:?]
at nukkitcoders.mobplugin.entities.monster.walking.Creeper.entityBaseTick(Creeper.java:192) [MobPlugin-1.17.1.jar:?]
at nukkitcoders.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:154) [MobPlugin-1.17.1.jar:?]
at cn.nukkit.level.Level.doTick(Level.java:943) [server.jar:?]
at cn.nukkit.Server.checkTickUpdates(Server.java:1295) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1377) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:1142) [server.jar:?]
at cn.nukkit.Server.start(Server.java:1102) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:762) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
Caused by: java.lang.ClassCastException: nukkitcoders.mobplugin.entities.monster.walking.Creeper cannot be cast to cn.nukkit.entity.item.EntityPrimedTNT
at com.boydti.rollback.CoreEvent.onBlockExplode(CoreEvent.java:286) ~[Rollback-1.0-SNAPSHOT.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:28) ~[server.jar:?]
... 12 more
02:11:56 [FATAL] Could not pass event "cn.nukkit.event.entity.EntityExplosionPrimeEvent" to "Rollback v1.0-SNAPSHOT": null on com.boydti.rollback.CoreEvent
02:11:56 [ERROR] Throwing
cn.nukkit.utils.EventException: null
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:33) ~[server.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:577) [server.jar:?]
at nukkitcoders.mobplugin.entities.monster.walking.Creeper.explode(Creeper.java:79) [MobPlugin-1.17.1.jar:?]
at nukkitcoders.mobplugin.entities.monster.walking.Creeper.entityBaseTick(Creeper.java:192) [MobPlugin-1.17.1.jar:?]
at nukkitcoders.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:154) [MobPlugin-1.17.1.jar:?]
at cn.nukkit.level.Level.doTick(Level.java:943) [server.jar:?]
at cn.nukkit.Server.checkTickUpdates(Server.java:1295) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1377) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:1142) [server.jar:?]
at cn.nukkit.Server.start(Server.java:1102) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:762) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
Caused by: java.lang.ClassCastException: nukkitcoders.mobplugin.entities.monster.walking.Creeper cannot be cast to cn.nukkit.entity.item.EntityPrimedTNT
at com.boydti.rollback.CoreEvent.onBlockExplode(CoreEvent.java:286) ~[Rollback-1.0-SNAPSHOT.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:28) ~[server.jar:?]
... 12 more

**Comment by PetteriM1** [comment]
Plugin issue: Rollback v1.0-SNAPSHOT
