### ISSUE TITLE
Error saving chunk

### ISSUE THREAD

**Issue by SS-YG** [Nukkit-coders/MobPlugin#213]
16:07:21 [ERROR] Throwing
cn.nukkit.utils.ChunkException: Error saving chunk (491, 484)
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:236) ~[PN.jar:?]
        at cn.nukkit.level.Level.unloadChunk(Level.java:3100) [PN.jar:?]
        at cn.nukkit.level.Level.unloadChunk(Level.java:3062) [PN.jar:?]
        at cn.nukkit.level.Level.unloadChunks(Level.java:3378) [PN.jar:?]
        at cn.nukkit.level.Level.unloadChunks(Level.java:3343) [PN.jar:?]
        at cn.nukkit.level.Level.unloadChunks(Level.java:3339) [PN.jar:?]
        at cn.nukkit.level.Level.doTick(Level.java:834) [PN.jar:?]
        at cn.nukkit.Server.checkTickUpdates(Server.java:1212) [PN.jar:?]
        at cn.nukkit.Server.tick(Server.java:1294) [PN.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1066) [PN.jar:?]
        at cn.nukkit.Server.start(Server.java:1034) [PN.jar:?]
        at cn.nukkit.Server.<init>(Server.java:695) [PN.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [PN.jar:?]
Caused by: java.lang.IllegalArgumentException: Empty string not allowed
        at cn.nukkit.nbt.tag.StringTag.<init>(StringTag.java:19) ~[PN.jar:?]
        at cn.nukkit.nbt.tag.CompoundTag.putString(CompoundTag.java:99) ~[PN.jar:?]
        at cn.nukkit.blockentity.BlockEntity.saveNBT(BlockEntity.java:179) ~[PN.jar:?]
        at nukkitcoders.mobplugin.entities.block.BlockEntitySpawner.saveNBT(BlockEntitySpawner.java:139) ~[MobPlugin.jar:?]
        at cn.nukkit.level.format.anvil.Chunk.toBinary(Chunk.java:383) ~[PN.jar:?]
        at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:152) ~[PN.jar:?]
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:234) ~[PN.jar:?]
        ... 12 more

**Comment by PetteriM1** [comment]
Can I have the debugpaste link please? 

Please follow the issue template when creating issue reports so maintainers don't need to spend their time asking for more info.

**Comment by SS-YG** [comment]
Sure!
https://hastebin.com/pejetazivi

**Comment by PetteriM1** [comment]
Unofficial Nukkit builds are not supported. Please create a new issue if you are able to reproduce this using the official builds.
