### ISSUE TITLE
nukkit.level.tickError NullPointerException

### ISSUE THREAD

**Issue by GoodLucky777** [Nukkit-coders/MobPlugin#235]
### Info

This is:
- [x] bug report
- [ ] feature request
- [x] other

### Your issue / suggestion

Sometimes MobPlugin error occur because of some plugins that remove players abnormally.
```
[main] ERROR - nukkit.level.tickError
java.lang.NullPointerException: null
	at nukkitcoders.mobplugin.entities.animal.walking.Donkey.targetOption(Donkey.java:59) ~[?:?]
	at nukkitcoders.mobplugin.entities.WalkingEntity.checkTarget(WalkingEntity.java:61) ~[?:?]
	at nukkitcoders.mobplugin.entities.HorseBase.checkTarget(HorseBase.java:218) ~[?:?]
	at nukkitcoders.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:191) ~[?:?]
	at nukkitcoders.mobplugin.entities.animal.WalkingAnimal.onUpdate(WalkingAnimal.java:73) ~[?:?]
	at nukkitcoders.mobplugin.entities.HorseBase.onUpdate(HorseBase.java:123) ~[?:?]
	at cn.nukkit.level.Level.doTick(Level.java:950) ~[powernukkit.jar:?]
	at cn.nukkit.Server.checkTickUpdates(Server.java:1296) [powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1378) [powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1143) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1103) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:775) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:199) [powernukkit.jar:?]
```

### Configuration
Config:
```
(Default config)
```

**Comment by PetteriM1** [comment]
Please include debugpaste and steps to reproduce when reporting bugs. Reopen if you can reproduce this on official Nukkit with no plugins that "remove players abnormally"
