### ISSUE TITLE
error in the console.

### ISSUE THREAD

**Issue by Mcayear** [Nukkit-coders/MobPlugin#245]
### Info

This is:
- [X] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
```2021-08-18 17:04:35.784 [main] ERROR - nukkit.level.tickError
java.lang.NullPointerException: null
	at nukkitcoders.mobplugin.entities.animal.walking.Pig.targetOption(Pig.java:72) ~[MobPlugin-1.21.0.jar:?]
	at nukkitcoders.mobplugin.entities.WalkingEntity.checkTarget(WalkingEntity.java:61) ~[MobPlugin-1.21.0.jar:?]
	at nukkitcoders.mobplugin.entities.animal.walking.Pig.checkTarget(Pig.java:219) ~[MobPlugin-1.21.0.jar:?]
	at nukkitcoders.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:191) ~[MobPlugin-1.21.0.jar:?]
	at nukkitcoders.mobplugin.entities.animal.WalkingAnimal.onUpdate(WalkingAnimal.java:64) ~[MobPlugin-1.21.0.jar:?]
	at nukkitcoders.mobplugin.entities.animal.walking.Pig.onUpdate(Pig.java:163) ~[MobPlugin-1.21.0.jar:?]
	at cn.nukkit.level.Level.doTick(Level.java:963) ~[powernukkit.jar:?]
	at cn.nukkit.Server.checkTickUpdates(Server.java:1289) [powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1371) [powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1143) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1103) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:775) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:199) [powernukkit.jar:?]
```
### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```
Version: MobPlugin-1.21.0.jar

**Comment by MonoAdrian23** [comment]
Same here

**Comment by PetteriM1** [comment]
Please report issues only on official Nukkit builds and debugpaste link included.
