### ISSUE TITLE
Error Log - Unknown Issue

### ISSUE THREAD

**Issue by Worthyofit** [Nukkit-coders/MobPlugin#273]
### Info

This is:
- [X ] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
IDK excatly what im doing here but i just put the error i got in for you, it just keeps spamming multiple times a second

### Configuration
Link to debugpaste:
```
2022-11-21 13:43:52.254 [main] ERROR - Could not pass event "cn.nukkit.event.server.DataPacketReceiveEvent" to "MobPlugin v1.24.0": null on nukkitcoders.mobplugin.EventListener
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:35) ~[nukkit.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:572) [nukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2432) [nukkit.jar:?]
	at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:153) [nukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:95) [nukkit.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:170) [nukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1363) [nukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1146) [nukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1106) [nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:778) [nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:200) [nukkit.jar:?]
Caused by: java.lang.NoClassDefFoundError: cn/nukkit/network/protocol/PlayerAuthInputPacket
	at nukkitcoders.mobplugin.EventListener.DataPacketReceiveEvent(EventListener.java:352) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:30) ~[nukkit.jar:?]
	... 11 more
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment]
Update to the latest Nukkit version

**Comment by Worthyofit** [comment]
I am using PowerNukkit 1.19.40 atm

**Comment by IWareQ** [comment]
> I am using PowerNukkit 1.19.40 atm

Use official nukkit, not fork's
