### ISSUE TITLE
service just broke down everytime I enable the plugin

### ISSUE THREAD

**Issue by MyFirmament** [Nukkit-coders/MobPlugin#73]
### Issue Description
Service just broke down everytime I enable the plugin.
I guess it happened when spawing mobs , because it crash seconds later when I load the plugin.

### Steps to Reproduce the Issue

NULL
just start the service

### Nukkit Version and Client Version

* Nukkit Version: 1.0 dev
* Client: Windows 10 ( v1.4)

#### Config.yml
```

default config

```
### Crashdump, Backtrace or Other Files
```
java.lang.NoClassDefFoundError: cn/nukkit/level/sound/Sound
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getField0(Class.java:2975)
	at java.lang.Class.getField(Class.java:1701)
	at cn.nukkit.entity.Entity.registerEntity(Entity.java:732)
	at cn.nukkit.entity.Entity.registerEntity(Entity.java:724)
	at com.pikycz.mobplugin.MobPlugin.registerEntities(MobPlugin.java:77)
	at com.pikycz.mobplugin.MobPlugin.onLoad(MobPlugin.java:38)
	at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:105)
	at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:53)
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:268)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
	at cn.nukkit.Server.<init>(Server.java:426)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.ClassNotFoundException: cn.nukkit.level.sound.Sound
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:34)
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more

```

**Comment by PetteriM1** [comment]
You are not using NukkitX? Try this old version of mob plugin: https://github.com/PetteriM1/MobPlugin-SuomiCraftPE

**Comment by MyFirmament** [comment]
But I download it from nukkitx.com ,,,

**Comment by PetteriM1** [comment]
You downloaded what from nukkitx.com?
This plugin works only with NukkitX, not with old Nukkit or multiversion.

**Comment by MyFirmament** [comment]
I download nukkit by click the "download" buttonon on nukkitx.com

**Comment by MyFirmament** [comment]
so you mean i am using nukkit not nukkitx?

**Comment by PetteriM1** [comment]
Or wait
From where did you download mob plugin?
com.pikycz.mobplugin.MobPlugin is not this plugin

**Comment by MyFirmament** [comment]
the same  form , in the tab "resources" .
I download both  nukkit and plugin today from the form to test.

**Comment by PetteriM1** [comment]
Last time: are you 100% sure you downloaded mob plugin from 
https://nukkitx.com/resources/mob-plugin.3/
or from
https://github.com/Nukkit-coders/MobPlugin/releases/tag/last
?
Because error message that you sent is not from this plugin. It's from PikyCZ's old outdated mob plugin. Download mob plugin from links above, check that there is no other mob plugins in plugins folder, restart server and if still error send full server.log file.

**Comment by MyFirmament** [comment]
OK ,thanks bro ~
i'll try it latter,thank for your explanation.
