### ISSUE TITLE
Reloading server starts error spamming

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit-coders/MobPlugin#75]
Problems started after 6c1d8d2
If I reload server after players have been online console starts spamming errors from route finder task

2018-6-16 13:11:07 [INFO] [CONSOLE: Uudelleenlataus valmis]
2018-6-16 13:11:07 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@44924587 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:07 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@44924587 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:07 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@4487c0c2 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:07 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@4487c0c2 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:07 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@3a08078c rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:07 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@3a08078c rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:08 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@396ef8b2 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:08 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@396ef8b2 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:08 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@19ee1ae6 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:08 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@19ee1ae6 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:09 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@1174a305 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:09 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@1174a305 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:09 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@1866da85 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:09 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@1866da85 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:10 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@78226c36 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:10 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@78226c36 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:10 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@11f406f8 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:10 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@11f406f8 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:11 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@622fdb81 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:11 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@622fdb81 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:11 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@2ec3633f rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:11 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@2ec3633f rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:12 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@13275d8 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:12 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@13275d8 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:12 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@20576557 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:12 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@20576557 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:13 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@45c2e0a6 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:13 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@45c2e0a6 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:13 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@a7ad6e5 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:13 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@a7ad6e5 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:14 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@690bc15e rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:14 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@690bc15e rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:14 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@475646d4 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:14 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@475646d4 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:15 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@3db972d2 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:15 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@3db972d2 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-6-16 13:11:15 [CRITICAL] Maailmaa "world" ei voida tickata: java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@687e4c93 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
2018-6-16 13:11:15 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@687e4c93 rejected from java.util.concurrent.ThreadPoolExecutor@18460128[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 269]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
	at cn.nukkit.level.Level.doTick(Level.java:757)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:850)
	at cn.nukkit.Server.start(Server.java:827)
	at cn.nukkit.Server.<init>(Server.java:510)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

@zzz1999 Do you know what causes this?

**Comment by zzz1999** [comment]
idk

**Comment by unresolvedsymbol** [comment]
@PetteriM1 Which commit fixed this?

**Comment by PetteriM1** [comment]
> @PetteriM1 Which commit fixed this?

19ba2fb
