### ISSUE TITLE
CRITICAL ALERT

### ISSUE THREAD

**Issue by EnterTG** [Nukkit-coders/MobPlugin#76]
### Issue Description

Write a short description about the issue

### Steps to Reproduce the Issue

1. Reload the server

### Nukkit Version and Client Version

* Nukkit Version: 1.2.5
* Client: Windows10

#### Config.yml
```

Default

```
### Crashdump, Backtrace or Other Files
12:32:03 [CRITICAL] Nie udalo sie obsluzyc operacji tick w pozomie"world": java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@5d260494 rejected from java.util.concurrent.ThreadPoolExecutor@3980b44f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 191]
12:32:03 [ALERT] java.util.concurrent.RejectedExecutionException: Task de.kniffo80.mobplugin.runnable.RouteFinderSearchTask@5d260494 rejected from java.util.concurrent.ThreadPoolExecutor@3980b44f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 191]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
        at de.kniffo80.mobplugin.RouteFinderThreadPool.executeRouteFinderThread(RouteFinderThreadPool.java:14)
        at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:142)
        at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:165)
        at cn.nukkit.level.Level.doTick(Level.java:757)
        at cn.nukkit.Server.checkTickUpdates(Server.java:1001)
        at cn.nukkit.Server.tick(Server.java:1087)
        at cn.nukkit.Server.tickProcessor(Server.java:850)
        at cn.nukkit.Server.start(Server.java:827)
        at cn.nukkit.Server.<init>(Server.java:510)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)

**Comment by PetteriM1** [comment]
This issue is already reported
https://github.com/Nukkit-coders/MobPlugin/issues/75
