### ISSUE TITLE
rabbit cause critical

### ISSUE THREAD

**Issue by wode490390** [Nukkit-coders/MobPlugin#94]
## Issue Description
console critical alert

## Steps to Reproduce the Issue
load chunk

## Nukkit Version and Client Version
- Nukkit Version: 1.6
- Client: Windows10

**Config.yml**

```
config-version: 2

entities:
  auto-spawn-tick: 200
  worlds-spawn-disabled: "exampleworld1,exampleworld2"
  despawn-entities: true
  despawn-ticks: 12000

max-spawns:
  bat: 2
  blaze: 4
  chicken: 8
  cow: 8
  creeper: 5
  enderman: 3
  ghast: 4
  husk: 2
  horse: 2
  mooshroom: 3
  ocelot: 2
  pig: 8
  polarbear: 3
  rabbit: 4
  stray: 2
  sheep: 8
  skeleton: 8
  spider: 8
  wolf: 3
  zombie: 10
```

## Crashdump, Backtrace or Other Files

```
2018-10-5 19:18:24 [CRITICAL] Could not tick level "{%0}": {%1}
java.lang.RuntimeException: Unmapped block registered
	at cn.nukkit.level.GlobalBlockPalette.getOrCreateRuntimeId(GlobalBlockPalette.java:58)
	at cn.nukkit.level.GlobalBlockPalette.getOrCreateRuntimeId(GlobalBlockPalette.java:51)
	at cn.nukkit.level.particle.PunchBlockParticle.<init>(PunchBlockParticle.java:20)
	at cn.nukkit.level.particle.PunchBlockParticle.<init>(PunchBlockParticle.java:15)
	at nukkitcoders.mobplugin.entities.animal.jumping.Rabbit.onUpdate(Rabbit.java:102)
	at cn.nukkit.level.Level.doTick(Level.java:771)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1004)
	at cn.nukkit.Server.tick(Server.java:1087)
	at cn.nukkit.Server.tickProcessor(Server.java:853)
	at cn.nukkit.Server.start(Server.java:830)
	at cn.nukkit.Server.<init>(Server.java:513)
	at cn.nukkit.Nukkit.main(Nukkit.java:109)
```

**Comment by PetteriM1** [comment]
Should be fixed now.
