### ISSUE TITLE
BlockEntitySpawner? NBT.

### ISSUE THREAD

**Issue by jdongel2004** [Nukkit-coders/MobPlugin#98]
19:43:10 [ALERT] java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at cn.nukkit.blockentity.BlockEntity.createBlockEntity(BlockEntity.java:113)        at cn.nukkit.level.format.generic.BaseFullChunk.initChunk(BaseFullChunk.java:156)
        at cn.nukkit.level.Level.forceLoadChunk(Level.java:2693)
        at cn.nukkit.level.Level.getChunk(Level.java:2356)
        at cn.nukkit.level.Level.populateChunk(Level.java:2915)
        at cn.nukkit.level.Level.populateChunk(Level.java:2906)
        at cn.nukkit.Player.sendNextChunk(Player.java:801)
        at cn.nukkit.Player.checkNetwork(Player.java:1816)
        at cn.nukkit.Server.tick(Server.java:1085)
        at cn.nukkit.Server.tickProcessor(Server.java:848)
        at cn.nukkit.Server.start(Server.java:825)
        at cn.nukkit.Server.<init>(Server.java:514)
        at cn.nukkit.Nukkit.main(Nukkit.java:109)
Caused by: java.lang.ClassCastException: cn.nukkit.nbt.tag.StringTag cannot be cast to cn.nukkit.nbt.tag.NumberTag
        at cn.nukkit.nbt.tag.CompoundTag.getInt(CompoundTag.java:145)
        at nukkitcoders.mobplugin.entities.block.BlockEntitySpawner.<init>(BlockEntitySpawner.java:48)
        ... 17 more

19:43:13 [ALERT] java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at cn.nukkit.blockentity.BlockEntity.createBlockEntity(BlockEntity.java:113)        at cn.nukkit.level.format.generic.BaseFullChunk.initChunk(BaseFullChunk.java:156)
        at cn.nukkit.level.Level.forceLoadChunk(Level.java:2693)
        at cn.nukkit.level.Level.getChunk(Level.java:2356)
        at cn.nukkit.level.Level.populateChunk(Level.java:2915)
        at cn.nukkit.level.Level.populateChunk(Level.java:2906)
        at cn.nukkit.Player.sendNextChunk(Player.java:801)
        at cn.nukkit.Player.checkNetwork(Player.java:1816)
        at cn.nukkit.Server.tick(Server.java:1085)
        at cn.nukkit.Server.tickProcessor(Server.java:848)
        at cn.nukkit.Server.start(Server.java:825)
        at cn.nukkit.Server.<init>(Server.java:514)
        at cn.nukkit.Nukkit.main(Nukkit.java:109)
Caused by: java.lang.ClassCastException: cn.nukkit.nbt.tag.StringTag cannot be cast to cn.nukkit.nbt.tag.NumberTag
        at cn.nukkit.nbt.tag.CompoundTag.getInt(CompoundTag.java:145)
        at nukkitcoders.mobplugin.entities.block.BlockEntitySpawner.<init>(BlockEntitySpawner.java:48)
        ... 17 more

19:43:13 [ALERT] java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at cn.nukkit.blockentity.BlockEntity.createBlockEntity(BlockEntity.java:113)        at cn.nukkit.level.format.generic.BaseFullChunk.initChunk(BaseFullChunk.java:156)
        at cn.nukkit.level.Level.forceLoadChunk(Level.java:2693)
        at cn.nukkit.level.Level.getChunk(Level.java:2356)
        at cn.nukkit.level.Level.populateChunk(Level.java:2915)
        at cn.nukkit.level.Level.populateChunk(Level.java:2906)
        at cn.nukkit.Player.sendNextChunk(Player.java:801)
        at cn.nukkit.Player.checkNetwork(Player.java:1816)
        at cn.nukkit.Server.tick(Server.java:1085)
        at cn.nukkit.Server.tickProcessor(Server.java:848)
        at cn.nukkit.Server.start(Server.java:825)
        at cn.nukkit.Server.<init>(Server.java:514)
        at cn.nukkit.Nukkit.main(Nukkit.java:109)
Caused by: java.lang.ClassCastException: cn.nukkit.nbt.tag.StringTag cannot be cast to cn.nukkit.nbt.tag.NumberTag
        at cn.nukkit.nbt.tag.CompoundTag.getInt(CompoundTag.java:145)
        at nukkitcoders.mobplugin.entities.block.BlockEntitySpawner.<init>(BlockEntitySpawner.java:48)
        ... 17 more

**Comment by PetteriM1** [comment]
When does this happen? What version? Could you give bit more information?

**Comment by jdongel2004** [comment]
The latest version is in use, and I don't know when it happens. (Just sometimes?) 
I'm korean, so My English is poor... sorry..
